# -*- coding: utf-8 -*-
"""Corelation Cofficient.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQM5ISKE8N7rTmERmneeRif2cCyNL3Y8
"""

import math
import matplotlib.pyplot as plot
N=int(input("Enter length of data"))
L1=[]
L2=[]
L3=[]
for i in range(0,N):
  a=float(input("Enter value of x  "))
  L1.append(a)
for i in range(0,N):
  b=float(input("Enter value of y  "))
  L2.append(b)
plot.scatter(L1,L2)
plot.show()
mode1=0
mode2=0
for i in range(0,N):
  mode1=mode1+L1[i]
  mode2=mode2+L2[i]
mode1=mode1/N
mode2=mode2/N
print(mode1,mode2)
for i in range(0,N):
  L1[i]=L1[i]-mode1
print("Xi-xbar =  ",L1)
for i in range(0,N):
  L2[i]=L2[i]-mode2
print("Yi-Ybar =  ",L2)
for i in range(0,N):
  L3.append(L1[i]*L2[i])
NSUM=0
for i in range(0,N):
  NSUM=NSUM+L3[i]
print(NSUM)
for i in range(0,N):
  L1[i]=L1[i]*L1[i]
  L2[i]=L2[i]*L2[i]
Dsum1=0
Dsum2=0
print("Xi-Xbar sq =  ",L1)
print("yi-ybar sq =  ",L2)
for i in range(0,N):
  Dsum1=Dsum1+L1[i]
  Dsum2=Dsum2+L2[i]
print("Denominator ",Dsum1,Dsum2)
Dsum=Dsum1*Dsum2
D_sum=math.sqrt(Dsum)
print(Dsum)
print("Denominator after sqrt  = ",D_sum)
r=NSUM/D_sum
print("Corelation coefficient :-  ",r)