# -*- coding: utf-8 -*-
"""Fibonacci_Series(Recursion).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTjep0jo-mwzhH12RXClACLEG0cvX03o
"""

arr=[0,1]
def fibonacci(a):
  if a<=0:
    return "Enter valid index"
  elif a<=len(arr):
    return arr[a-1]
  else:
    b=fibonacci(a-1)+fibonacci(a-2)
    arr.append(b)
    return b


print(fibonacci(9))