# -*- coding: utf-8 -*-
"""Making_Coin_change.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXjqOs8X48F_5df8myGMGr89b-6GxCCK
"""

def makingcoinchange(coin,amt):
  table = [0 for i in range(amt+1)]
  table[0]=1
  for i in range(len(coin)):
    for j in range(coin[i],amt+1):
      table[j]=table[j]+table[j-coin[i]]
  return table[amt]

coin=[2,3,5,10]
amt=15
print(makingcoinchange(coin,amt))