# -*- coding: utf-8 -*-
"""Mean_Median_Mode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgXVqwnDPSyVhC99I9YWEvmLfoU2dmBF
"""

import random
no = int(input("Enter the number of times you want to Roll The Dice    "))
ls=[]
for i in range(0,no):
  ls.append(random.randint(1,6))
print(ls)
mean=0
for i in ls:
  mean=mean + i
print("Mean = ",round((mean/no),2))
ls.sort()
if(no%2==0):
  median=(ls[no//2]+ls[(no-1)//2])/2
else:
  median = ls[no//2]
print("Median =  ",median)

import collections
data=collections.Counter(ls)
data_list=dict(data)
print(data_list)
max_value = max(list(data.values()))
mode_val = [num for num, freq in data_list.items() if freq == max_value]
if len(mode_val) == no:
   print("No mode in the list")
else:
   print("The Mode of the list is : " + ', '.join(map(str, mode_val)))